name: First Workflow
on: workflow_distpatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Hello world"
      - name: step-2
        run: echo "Done - Bye!"
    
